// Override miryoku layer bindings to include Lily58 extended keys and profile layers.

#pragma once

#include "extended_keys.h"
#include "wrap.h"
#include "game_layer.h"

#undef MIRYOKU_LAYER_BASE
#undef MIRYOKU_LAYER_EXTRA
#undef MIRYOKU_LAYER_TAP
#undef MIRYOKU_LAYER_BUTTON
#undef MIRYOKU_LAYER_NAV
#undef MIRYOKU_LAYER_MOUSE
#undef MIRYOKU_LAYER_MEDIA
#undef MIRYOKU_LAYER_NUM
#undef MIRYOKU_LAYER_SYM
#undef MIRYOKU_LAYER_FUN

#define MIRYOKU_LAYER_BASE   MIRYOKU_WRAP_MIRYOKU(MIRYOKU_ALTERNATIVES_BASE_QWERTY)
#define MIRYOKU_LAYER_EXTRA  MIRYOKU_WRAP_MIRYOKU(MIRYOKU_ALTERNATIVES_BASE_QWERTY)
#define MIRYOKU_LAYER_TAP    MIRYOKU_WRAP_MIRYOKU(MIRYOKU_ALTERNATIVES_TAP_QWERTY)
#define MIRYOKU_LAYER_BUTTON MIRYOKU_WRAP_MIRYOKU(MIRYOKU_ALTERNATIVES_BUTTON)
#define MIRYOKU_LAYER_NAV    MIRYOKU_WRAP_MIRYOKU(MIRYOKU_ALTERNATIVES_NAV)
#define MIRYOKU_LAYER_MOUSE  MIRYOKU_WRAP_MIRYOKU(MIRYOKU_ALTERNATIVES_MOUSE)
#define MIRYOKU_LAYER_MEDIA  MIRYOKU_WRAP_MIRYOKU(MIRYOKU_ALTERNATIVES_MEDIA)
#define MIRYOKU_LAYER_NUM    MIRYOKU_WRAP_MIRYOKU(MIRYOKU_ALTERNATIVES_NUM)
#define MIRYOKU_LAYER_SYM    MIRYOKU_WRAP_MIRYOKU(MIRYOKU_ALTERNATIVES_SYM)
#define MIRYOKU_LAYER_FUN    MIRYOKU_WRAP_MIRYOKU(MIRYOKU_ALTERNATIVES_FUN)
