// Auto-generated by scripts/gen-wrapped-layers.py — do not edit.
// Alpha layout: MIRYOKU_ALPHAS_COLEMAK
#pragma once

#include "extended_keys.h"
#include "diagnostics.h"

#define MIRYOKU_LAYER_BASE \
  &none, &none, &none, ML_SEL_MIRYOKU, ML_SEL_GAME, ML_SEL_SLOT3, \
  &none, &none, &none, &none, &none, &kp N1, \
  &none, &kp Q, &kp W, &kp F, &kp P, &kp G, \
  &kp J, &kp L, &kp U, &kp Y, &kp SQT, &none, \
  &none, U_MT(LGUI, A), U_MT(LALT, R), U_MT(LCTRL, S), U_MT(LSHFT, T), &kp D, \
  &kp H, U_MT(LSHFT, N), U_MT(LCTRL, E), U_MT(LALT, I), U_MT(LGUI, O), &none, \
  &none, U_LT(U_BUTTON, Z), U_MT(RALT, X), &kp C, &kp V, &kp B, \
  &kp K, &kp M, &kp COMMA, U_MT(RALT, DOT), U_LT(U_BUTTON, SLASH), &none, \
  U_NP, U_NP, U_LT(U_MEDIA, ESC), U_LT(U_NAV, SPACE), U_LT(U_MOUSE, TAB), U_LT(U_SYM, RET), \
  U_LT(U_NUM, BSPC), U_LT(U_FUN, DEL), U_NP, U_NP

#define MIRYOKU_LAYER_EXTRA \
  &none, &none, &none, ML_SEL_MIRYOKU, ML_SEL_GAME, ML_SEL_SLOT3, \
  &none, &none, &none, &none, &none, &kp N2, \
  &none, &kp Q, &kp W, &kp F, &kp P, &kp G, \
  &kp J, &kp L, &kp U, &kp Y, &kp SQT, &none, \
  &none, U_MT(LGUI, A), U_MT(LALT, R), U_MT(LCTRL, S), U_MT(LSHFT, T), &kp D, \
  &kp H, U_MT(LSHFT, N), U_MT(LCTRL, E), U_MT(LALT, I), U_MT(LGUI, O), &none, \
  &none, U_LT(U_BUTTON, Z), U_MT(RALT, X), &kp C, &kp V, &kp B, \
  &kp K, &kp M, &kp COMMA, U_MT(RALT, DOT), U_LT(U_BUTTON, SLASH), &none, \
  U_NP, U_NP, U_LT(U_MEDIA, ESC), U_LT(U_NAV, SPACE), U_LT(U_MOUSE, TAB), U_LT(U_SYM, RET), \
  U_LT(U_NUM, BSPC), U_LT(U_FUN, DEL), U_NP, U_NP

#define MIRYOKU_LAYER_TAP \
  &none, &none, &none, ML_SEL_MIRYOKU, ML_SEL_GAME, ML_SEL_SLOT3, \
  &none, &none, &none, &none, &none, &kp N3, \
  &none, &kp Q, &kp W, &kp F, &kp P, &kp G, \
  &kp J, &kp L, &kp U, &kp Y, &kp SQT, &none, \
  &none, &kp A, &kp R, &kp S, &kp T, &kp D, \
  &kp H, &kp N, &kp E, &kp I, &kp O, &none, \
  &none, &kp Z, &kp X, &kp C, &kp V, &kp B, \
  &kp K, &kp M, &kp COMMA, &kp DOT, &kp SLASH, &none, \
  U_NP, U_NP, &kp ESC, &kp SPACE, &kp TAB, &kp RET, \
  &kp BSPC, &kp DEL, U_NP, U_NP

#define MIRYOKU_LAYER_BUTTON \
  &none, &none, &none, ML_SEL_MIRYOKU, ML_SEL_GAME, ML_SEL_SLOT3, \
  &none, &none, &none, &none, &none, &kp N4, \
  &none, U_UND, U_CUT, U_CPY, U_PST, U_RDO, \
  U_RDO, U_PST, U_CPY, U_CUT, U_UND, &none, \
  &none, &kp LGUI, &kp LALT, &kp LCTRL, &kp LSHFT, U_NU, \
  U_NU, &kp LSHFT, &kp LCTRL, &kp LALT, &kp LGUI, &none, \
  &none, U_UND, U_CUT, U_CPY, U_PST, U_RDO, \
  U_RDO, U_PST, U_CPY, U_CUT, U_UND, &none, \
  U_NP, U_NP, U_BTN3, U_BTN1, U_BTN2, U_BTN2, \
  U_BTN1, U_BTN3, U_NP, U_NP

#define MIRYOKU_LAYER_NAV \
  &none, &none, &none, ML_SEL_MIRYOKU, ML_SEL_GAME, ML_SEL_SLOT3, \
  &none, &none, &none, &none, &none, &kp N5, \
  &none, U_BOOT, &u_to_U_TAP, &u_to_U_EXTRA, &u_to_U_BASE, U_NA, \
  U_RDO, U_PST, U_CPY, U_CUT, U_UND, &none, \
  &none, &kp LGUI, &kp LALT, &kp LCTRL, &kp LSHFT, U_NA, \
  &u_caps_word, &kp LEFT, &kp DOWN, &kp UP, &kp RIGHT, &none, \
  &none, U_NA, &kp RALT, &u_to_U_NUM, &u_to_U_NAV, U_NA, \
  &kp INS, &kp HOME, &kp PG_DN, &kp PG_UP, &kp END, &none, \
  U_NP, U_NP, U_NA, U_NA, U_NA, &kp RET, \
  &kp BSPC, &kp DEL, U_NP, U_NP

#define MIRYOKU_LAYER_MOUSE \
  &none, &none, &none, ML_SEL_MIRYOKU, ML_SEL_GAME, ML_SEL_SLOT3, \
  &none, &none, &none, &none, &none, &kp N6, \
  &none, U_BOOT, &u_to_U_TAP, &u_to_U_EXTRA, &u_to_U_BASE, U_NA, \
  U_RDO, U_PST, U_CPY, U_CUT, U_UND, &none, \
  &none, &kp LGUI, &kp LALT, &kp LCTRL, &kp LSHFT, U_NA, \
  U_NU, U_MS_L, U_MS_D, U_MS_U, U_MS_R, &none, \
  &none, U_NA, &kp RALT, &u_to_U_SYM, &u_to_U_MOUSE, U_NA, \
  U_NU, U_WH_L, U_WH_D, U_WH_U, U_WH_R, &none, \
  U_NP, U_NP, U_NA, U_NA, U_NA, U_BTN2, \
  U_BTN1, U_BTN3, U_NP, U_NP

#define MIRYOKU_LAYER_MEDIA \
  &none, &none, &none, ML_SEL_MIRYOKU, ML_SEL_GAME, ML_SEL_SLOT3, \
  &none, &none, &none, &none, &none, &kp N7, \
  &none, U_BOOT, &u_to_U_TAP, &u_to_U_EXTRA, &u_to_U_BASE, U_NA, \
  U_RGB_TOG, U_RGB_EFF, U_RGB_HUI, U_RGB_SAI, U_RGB_BRI, &none, \
  &none, &kp LGUI, &kp LALT, &kp LCTRL, &kp LSHFT, U_NA, \
  U_EP_TOG, &kp C_PREV, &kp C_VOL_DN, &kp C_VOL_UP, &kp C_NEXT, &none, \
  &none, U_NA, &kp RALT, &u_to_U_FUN, &u_to_U_MEDIA, U_NA, \
  &u_out_tog, &u_bt_sel_0, &u_bt_sel_1, &u_bt_sel_2, &u_bt_sel_3, &none, \
  U_NP, U_NP, U_NA, U_NA, U_NA, &kp C_STOP, \
  &kp C_PP, &kp C_MUTE, U_NP, U_NP

#define MIRYOKU_LAYER_NUM \
  &none, &none, &none, ML_SEL_MIRYOKU, ML_SEL_GAME, ML_SEL_SLOT3, \
  &none, &none, &none, &none, &none, &kp N8, \
  &none, &kp LBKT, &kp N7, &kp N8, &kp N9, &kp RBKT, \
  U_NA, &u_to_U_BASE, &u_to_U_EXTRA, &u_to_U_TAP, U_BOOT, &none, \
  &none, &kp SEMI, &kp N4, &kp N5, &kp N6, &kp EQUAL, \
  U_NA, &kp LSHFT, &kp LCTRL, &kp LALT, &kp LGUI, &none, \
  &none, &kp GRAVE, &kp N1, &kp N2, &kp N3, &kp BSLH, \
  U_NA, &u_to_U_NUM, &u_to_U_NAV, &kp RALT, U_NA, &none, \
  U_NP, U_NP, &kp DOT, &kp N0, &kp MINUS, U_NA, \
  U_NA, U_NA, U_NP, U_NP

#define MIRYOKU_LAYER_SYM \
  &none, &none, &none, ML_SEL_MIRYOKU, ML_SEL_GAME, ML_SEL_SLOT3, \
  &none, &none, &none, &none, &none, &kp N9, \
  &none, &kp LBRC, &kp AMPS, &kp ASTRK, &kp LPAR, &kp RBRC, \
  U_NA, &u_to_U_BASE, &u_to_U_EXTRA, &u_to_U_TAP, U_BOOT, &none, \
  &none, &kp COLON, &kp DLLR, &kp PRCNT, &kp CARET, &kp PLUS, \
  U_NA, &kp LSHFT, &kp LCTRL, &kp LALT, &kp LGUI, &none, \
  &none, &kp TILDE, &kp EXCL, &kp AT, &kp HASH, &kp PIPE, \
  U_NA, &u_to_U_SYM, &u_to_U_MOUSE, &kp RALT, U_NA, &none, \
  U_NP, U_NP, &kp LPAR, &kp RPAR, &kp UNDER, U_NA, \
  U_NA, U_NA, U_NP, U_NP

#define MIRYOKU_LAYER_FUN \
  &none, &none, &none, ML_SEL_MIRYOKU, ML_SEL_GAME, ML_SEL_SLOT3, \
  &none, &none, &none, &none, &none, &kp N0, \
  &none, &kp F12, &kp F7, &kp F8, &kp F9, &kp PSCRN, \
  U_NA, &u_to_U_BASE, &u_to_U_EXTRA, &u_to_U_TAP, U_BOOT, &none, \
  &none, &kp F11, &kp F4, &kp F5, &kp F6, &kp SLCK, \
  U_NA, &kp LSHFT, &kp LCTRL, &kp LALT, &kp LGUI, &none, \
  &none, &kp F10, &kp F1, &kp F2, &kp F3, &kp PAUSE_BREAK, \
  U_NA, &u_to_U_FUN, &u_to_U_MEDIA, &kp RALT, U_NA, &none, \
  U_NP, U_NP, &kp K_APP, &kp SPACE, &kp TAB, U_NA, \
  U_NA, U_NA, U_NP, U_NP
