#!/usr/bin/env python3
"""Generate multi_layout/wrapped_layers.h from miryoku alternatives + wrap.h layout."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BABEL = ROOT / "miryoku" / "miryoku_babel" / "miryoku_layer_alternatives.h"
OUT = ROOT / "miryoku" / "multi_layout" / "wrapped_layers.h"

LAYER_ALTS = {
    "BASE": "MIRYOKU_ALTERNATIVES_BASE_QWERTY",
    "EXTRA": "MIRYOKU_ALTERNATIVES_BASE_QWERTY",
    "TAP": "MIRYOKU_ALTERNATIVES_TAP_QWERTY",
    "BUTTON": "MIRYOKU_ALTERNATIVES_BUTTON",
    "NAV": "MIRYOKU_ALTERNATIVES_NAV",
    "MOUSE": "MIRYOKU_ALTERNATIVES_MOUSE",
    "MEDIA": "MIRYOKU_ALTERNATIVES_MEDIA",
    "NUM": "MIRYOKU_ALTERNATIVES_NUM",
    "SYM": "MIRYOKU_ALTERNATIVES_SYM",
    "FUN": "MIRYOKU_ALTERNATIVES_FUN",
}

ML_MIRYOKU_L_TOP = [
    "&kp F13",
    "&kp F14",
    "&kp F15",
    "&kp F16",
    "&kp F17",
    "&kp F18",
]
ML_LAYOUT_SELECT = [
    "ML_SEL_MIRYOKU",
    "ML_SEL_GAME",
    "ML_SEL_SLOT3",
    "U_NA",
    "U_NA",
    "U_NA",
]


def split_top_level_commas(text: str) -> list[str]:
    parts: list[str] = []
    depth = 0
    start = 0
    for i, c in enumerate(text):
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
        elif c == "," and depth == 0:
            part = text[start:i].strip()
            if part:
                parts.append(part)
            start = i + 1
    tail = text[start:].strip()
    if tail:
        parts.append(tail)
    return parts


def extract_alternatives(src: str, macro: str) -> list[str]:
    needle = f"#define {macro} "
    start = src.find(needle)
    if start < 0:
        needle = f"#define {macro}\\\n"
        start = src.find(needle)
    if start < 0:
        raise SystemExit(f"macro not found: {macro}")
    rest = src[start + len(needle) :]
    end = rest.find("\n#define ")
    if end < 0:
        end = len(rest)
    body = rest[:end]
    body = re.sub(r"\\\s*\n\s*", " ", body)
    parts = split_top_level_commas(body)
    if len(parts) != 40:
        raise SystemExit(f"{macro}: expected 40 bindings, got {len(parts)}")
    return parts


def wrap_miryoku(alts: list[str]) -> list[str]:
    if len(alts) != 40:
        raise ValueError(f"expected 40 alts, got {len(alts)}")
    return [
        *ML_MIRYOKU_L_TOP,
        *ML_LAYOUT_SELECT,
        "&kp F19",
        *alts[0:10],
        "&kp F22",
        "&kp F20",
        *alts[10:20],
        "&kp F23",
        "&kp F21",
        *alts[20:30],
        "&kp F24",
        *alts[30:40],
    ]


def format_layer(name: str, bindings: list[str]) -> str:
    lines = [f"#define MIRYOKU_LAYER_{name} \\"]
    row = []
    for i, b in enumerate(bindings):
        row.append(b)
        if len(row) >= 6 or i == len(bindings) - 1:
            cont = i < len(bindings) - 1
            lines.append("  " + ", ".join(row) + ("," if cont else "") + (" \\" if cont else ""))
            row = []
    return "\n".join(lines)


def main() -> int:
    src = BABEL.read_text()
    chunks = [
        "// Auto-generated by scripts/gen-wrapped-layers.py — do not edit.",
        "#pragma once",
        "",
        "#include \"extended_keys.h\"",
        "",
    ]
    for layer, alts_macro in LAYER_ALTS.items():
        alts = extract_alternatives(src, alts_macro)
        wrapped = wrap_miryoku(alts)
        if len(wrapped) != 58:
            raise SystemExit(f"{layer}: wrap produced {len(wrapped)} bindings, expected 58")
        chunks.append(format_layer(layer, wrapped))
        chunks.append("")
    OUT.write_text("\n".join(chunks))
    print(f"Wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
