#!/usr/bin/env python3
"""Generate multi_layout/wrapped_layers.h from miryoku alternatives + wrap.h layout."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BABEL = ROOT / "miryoku" / "miryoku_babel" / "miryoku_layer_alternatives.h"
CONFIG = ROOT / "miryoku" / "custom_config.h"
OUT = ROOT / "miryoku" / "multi_layout" / "wrapped_layers.h"

ALPHA_LAYOUTS = (
    "AZERTY",
    "BEAKL15",
    "COLEMAK",
    "COLEMAKDH",
    "COLEMAKDHK",
    "DVORAK",
    "HALMAK",
    "WORKMAN",
    "QWERTY",
    "QWERTZ",
)

ML_MIRYOKU_L_TOP = [
    "&none",
    "&none",
    "&none",
    "ML_SEL_MIRYOKU",
    "ML_SEL_GAME",
    "ML_SEL_SLOT3",
]
ML_LAYOUT_SELECT_RIGHT = [
    "&none",
    "&none",
    "&none",
    "&none",
    "&none",
    "U_NA",
]

# Index of K54 in MIRYOKU_BIND_LILY58 (s49..s54 → K54 is index 11).
K54_BIND_INDEX = 11

K54_DIAG = {
    0: "&kp N1",
    1: "&kp N2",
    2: "&kp N3",
    3: "&kp N4",
    4: "&kp N5",
    5: "&kp N6",
    6: "&kp N7",
    7: "&kp N8",
    8: "&kp N9",
    9: "&kp N0",
    10: "&kp A",
    11: "&kp B",
}


def alpha_layout_from_config(config: str) -> str:
    for layout in ALPHA_LAYOUTS:
        if re.search(rf"^#define\s+MIRYOKU_ALPHAS_{layout}\s*$", config, re.M):
            return layout
    raise SystemExit(
        "custom_config.h: set exactly one MIRYOKU_ALPHAS_* (e.g. MIRYOKU_ALPHAS_DVORAK)"
    )


def alpha_suffix(config: str) -> str:
    return "_FLIP" if re.search(r"^#define\s+MIRYOKU_LAYERS_FLIP\s*$", config, re.M) else ""


def layer_alts(config: str) -> list[tuple[str, str, int]]:
    layout = alpha_layout_from_config(config)
    suffix = alpha_suffix(config)
    base = f"MIRYOKU_ALTERNATIVES_BASE_{layout}{suffix}"
    tap = f"MIRYOKU_ALTERNATIVES_TAP_{layout}{suffix}"
    # Order matches layer_list.h / U_* indices for K54 diagnostics.
    return [
        ("BASE", base, 0),
        ("EXTRA", base, 1),
        ("TAP", tap, 2),
        ("BUTTON", "MIRYOKU_ALTERNATIVES_BUTTON", 3),
        ("NAV", "MIRYOKU_ALTERNATIVES_NAV", 4),
        ("MOUSE", "MIRYOKU_ALTERNATIVES_MOUSE", 5),
        ("MEDIA", "MIRYOKU_ALTERNATIVES_MEDIA", 6),
        ("NUM", "MIRYOKU_ALTERNATIVES_NUM", 7),
        ("SYM", "MIRYOKU_ALTERNATIVES_SYM", 8),
        ("FUN", "MIRYOKU_ALTERNATIVES_FUN", 9),
    ]


def split_top_level_commas(text: str) -> list[str]:
    parts: list[str] = []
    depth = 0
    start = 0
    for i, c in enumerate(text):
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
        elif c == "," and depth == 0:
            part = text[start:i].strip()
            if part:
                parts.append(part)
            start = i + 1
    tail = text[start:].strip()
    if tail:
        parts.append(tail)
    return parts


def extract_alternatives(src: str, macro: str) -> list[str]:
    needle = f"#define {macro} "
    start = src.find(needle)
    if start < 0:
        needle = f"#define {macro}\\\n"
        start = src.find(needle)
    if start < 0:
        raise SystemExit(f"macro not found: {macro}")
    rest = src[start + len(needle) :]
    end = rest.find("\n#define ")
    if end < 0:
        end = len(rest)
    body = rest[:end]
    body = re.sub(r"\\\s*\n\s*", " ", body)
    parts = split_top_level_commas(body)
    if len(parts) != 40:
        raise SystemExit(f"{macro}: expected 40 bindings, got {len(parts)}")
    return parts


def wrap_miryoku(alts: list[str], layer_index: int) -> list[str]:
    if len(alts) != 40:
        raise ValueError(f"expected 40 alts, got {len(alts)}")
    bindings = [
        *ML_MIRYOKU_L_TOP,
        *ML_LAYOUT_SELECT_RIGHT,
        "&none",
        *alts[0:10],
        "&none",
        "&none",
        *alts[10:20],
        "&none",
        "&none",
        *alts[20:25],
        *alts[38:40],
        *alts[25:30],
        "&none",
        *alts[30:38],
    ]
    bindings[K54_BIND_INDEX] = K54_DIAG[layer_index]
    return bindings


def format_layer(name: str, bindings: list[str]) -> str:
    lines = [f"#define MIRYOKU_LAYER_{name} \\"]
    row = []
    for i, b in enumerate(bindings):
        row.append(b)
        if len(row) >= 6 or i == len(bindings) - 1:
            cont = i < len(bindings) - 1
            lines.append("  " + ", ".join(row) + ("," if cont else "") + (" \\" if cont else ""))
            row = []
    return "\n".join(lines)


def main() -> int:
    config = CONFIG.read_text()
    src = BABEL.read_text()
    alts_list = layer_alts(config)
    layout = alpha_layout_from_config(config)
    chunks = [
        "// Auto-generated by scripts/gen-wrapped-layers.py — do not edit.",
        f"// Alpha layout: MIRYOKU_ALPHAS_{layout}{alpha_suffix(config)}",
        "#pragma once",
        "",
        "#include \"extended_keys.h\"",
        "#include \"diagnostics.h\"",
        "",
    ]
    for layer, alts_macro, layer_index in alts_list:
        alts = extract_alternatives(src, alts_macro)
        wrapped = wrap_miryoku(alts, layer_index)
        if len(wrapped) != 58:
            raise SystemExit(f"{layer}: wrap produced {len(wrapped)} bindings, expected 58")
        chunks.append(format_layer(layer, wrapped))
        chunks.append("")
    OUT.write_text("\n".join(chunks))
    print(f"Wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
